apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  labels:
    type: demo
spec:
  selector:
    matchLabels:
      type: demo
      app: todo-app
  replicas: 3
  template:
    metadata:
      labels:
        type: demo
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: flask-todo-app
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
