apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  labels:
    type: demo
spec:
  selector:
    matchLabels:
      type: demo
      app: todo-app
  replicas: 3
  template:
    metadata:
      labels:
        type: demo
        app: todo-app
    spec:
      containers:
      - name: flask-todo-app
        image: todo-app
        imagePullPolicy: Never
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 5000
